from typing import Any

class FinalizeError(Exception): ...

class _ModuleProxy:
    def __init__(self, fm): ...

class _ModuleComb(_ModuleProxy):
    def __iadd__(self, other): ...

class _ModuleSync(_ModuleProxy):
    def __iadd__(self, other): ...

class _ModuleForwardAttr: ...

class _ModuleSpecials(_ModuleProxy, _ModuleForwardAttr):
    def __iadd__(self, other): ...

class _ModuleSubmodules(_ModuleProxy):
    def __iadd__(self, other): ...

class _ModuleClockDomains(_ModuleProxy, _ModuleForwardAttr):
    def __iadd__(self, other): ...

class Module:
    comb: _ModuleComb
    sync: _ModuleSync
    specials: _ModuleSpecials
    submodules: _ModuleSubmodules
    clock_domains: _ModuleClockDomains
    finalized: bool
    get_fragment_called: bool
    def get_fragment(self): ...
    def finalize(self, *args, **kwargs): ...
    def do_finalize(self): ...
    def do_exit(self, *args, **kwargs): ...
